### ISSUE TITLE
Status "finished" when the status in the Scrapy Cloud is "banned"

### ISSUE THREAD

**Issue by noviluni** [realslimshanky/Spider-Sense#1]
I've been using this extension some days and I really like it. Congrats!

However I found this behaviour a little annoying, as the appearing "status" in the extension differ from the "status" in the Scrapy Cloud. I didn't go through the code and I don't know if it's an API limitation, but it could be a good to have feature if it's feasible.

**Comment by realslimshanky** [comment]
Thanks @noviluni for the issue. This is due to incorrectly fetching the key to the reason why the job is finished. A minor fix will work. I'll take care of it.
